module.exports = [
	{ title: 'none', value: '' },
	{ title: 'award', value: 'awards' },
	{ title: 'bank', value: 'bank' },
	{ title: 'book', value: 'book-alt' },
	{ title: 'calendar', value: 'calendar-alt' },
	{ title: 'chat bubbles', value: 'format-chat' },
	{ title: 'drink', value: 'coffee' },
	{ title: 'food', value: 'food' },
	{ title: 'globe', value: 'admin-site' },
	{ title: 'graduation cap', value: 'welcome-learn-more' },
	{ title: 'help icon', value: 'editor-help' },
	{ title: 'home', value: 'admin-home' },
	{ title: 'homes', value: 'admin-multisite' },
	{ title: 'image', value: 'format-image' },
	{ title: 'images', value: 'format-gallery' },
	{ title: 'info icon', value: 'info' },
	{ title: 'key', value: 'admin-network' },
	{ title: 'map marker', value: 'location' },
	{ title: 'map with pin', value: 'location-alt' },
	{ title: 'megaphone', value: 'megaphone' },
	{ title: 'padlock', value: 'lock' },
	{ title: 'palette', value: 'art' },
	{ title: 'palm tree', value: 'palmtree' },
	{ title: 'push pin', value: 'admin-post' },
	{ title: 'quote', value: 'format-quote' },
	{ title: 'shopping bag', value: 'products' },
	{ title: 'shopping cart', value: 'cart' },
	{ title: 'smiley', value: 'smiley' },
	{ title: 'speech bubble', value: 'format-status' },
	{ title: 'star', value: 'star-filled' },
	{ title: 'store', value: 'store' },
	{ title: 'thumbs up', value: 'thumbs-up' },
	{ title: 'tickets', value: 'tickets-alt' },
	{ title: 'user', value: 'admin-users' },
	{ title: 'users', value: 'groups' },
	{ title: 'video', value: 'video-alt3' },
];